import Head from 'next/head'
import Link from 'next/link';
import { motion } from "framer-motion"
import { BsSearch } from "react-icons/bs";
import Logo from '../components/Logo';

import datas from "../lib/data.json"


export default function Home() {


  return (
    <div>
      <Head>
        <title>Manga Panel</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Logo */}
      <Logo />
      
      {/* Titre */}
      <div className="text-center mt-10 mx-10">
        <h1 className="text-white text-2xl sm:text-5xl font-light tracking-widest mb-[30px] sm:mb-5">Freedom|Manga</h1>
        <span className="text-orange-400">Attention Spoiler ! Certaines planches peuvent vous spoiler, si vous n'êtes pas à jour.</span>
      </div>

      {/* Barre de recherche */}
      <div className="flex justify-center items-center mt-[30px] sm:mt-[40px]">
        <input className="w-[250px] sm:w-[50%] pl-3 py-[10px] sm:py-[15px] bg-[#727272] rounded-l-[10px] text-white outline-none" placeholder="Cherchez votre manga..." />
        <div className="bg-[#727272] px-[10px] py-[12px] sm:py-[17px] rounded-r-[10px]">
          <BsSearch color='white' font-size='20' />
        </div>
      </div>

      {/* Manga */}
      <div className="my-10 grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-5 place-items-center justify-self-center mx-10 md:mx-[23%]">
          {datas.map((d) => {

            return(        
              <motion.div whileHover={{ scale: 1.05 }} className="cursor-pointer" key={d.id}>      
                <Link href={{
                  pathname: "manga/[id]",
                  query: {
                    id: d.id,
                    name: d.name,
                    auteur: d.auteur,
                    img: d.img
                  }
                }}>
                  <img className="h-[120px] sm:h-40 rounded-[10px]" src={d.icon} alt="" />
                </Link>
                <span className="text-white text-[16px] font-light tracking-widest">{d.name}</span>
              </motion.div>
            )
          })}
      </div>
    </div>
  )
}
